# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/qtimidity.ui'
#
# Created: Mon Oct 12 12:48:01 2009
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(534, 308)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/32x32/qtimidity-icon-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.homeButton = QtGui.QToolButton(self.centralwidget)
        self.homeButton.setIconSize(QtCore.QSize(22, 22))
        self.homeButton.setAutoRaise(True)
        self.homeButton.setObjectName("homeButton")
        self.horizontalLayout.addWidget(self.homeButton)
        self.upButton = QtGui.QToolButton(self.centralwidget)
        self.upButton.setIconSize(QtCore.QSize(22, 22))
        self.upButton.setAutoRaise(True)
        self.upButton.setObjectName("upButton")
        self.horizontalLayout.addWidget(self.upButton)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.VLine)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        self.prevButton = QtGui.QToolButton(self.centralwidget)
        self.prevButton.setIconSize(QtCore.QSize(22, 22))
        self.prevButton.setAutoRaise(True)
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout.addWidget(self.prevButton)
        self.stopButton = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setIconSize(QtCore.QSize(22, 22))
        self.stopButton.setAutoRaise(True)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.playButton = QtGui.QToolButton(self.centralwidget)
        self.playButton.setIconSize(QtCore.QSize(22, 22))
        self.playButton.setAutoRaise(True)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout.addWidget(self.playButton)
        self.nextButton = QtGui.QToolButton(self.centralwidget)
        self.nextButton.setIconSize(QtCore.QSize(22, 22))
        self.nextButton.setAutoRaise(True)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.navigationView = QtGui.QListView(self.splitter)
        self.navigationView.setDragEnabled(True)
        self.navigationView.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.navigationView.setAlternatingRowColors(True)
        self.navigationView.setObjectName("navigationView")
        self.playtableView = QtGui.QTableView(self.splitter)
        self.playtableView.setDragEnabled(True)
        self.playtableView.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.playtableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.playtableView.setShowGrid(False)
        self.playtableView.setSortingEnabled(False)
        self.playtableView.setObjectName("playtableView")
        self.playtableView.horizontalHeader().setVisible(False)
        self.playtableView.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.splitter)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 534, 22))
        self.menubar.setObjectName("menubar")
        self.menuQtimidity = QtGui.QMenu(self.menubar)
        self.menuQtimidity.setObjectName("menuQtimidity")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuPlaylist = QtGui.QMenu(self.menubar)
        self.menuPlaylist.setObjectName("menuPlaylist")
        self.menu_Go = QtGui.QMenu(self.menubar)
        self.menu_Go.setObjectName("menu_Go")
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNext = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/48x48/media-skip-forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext.setIcon(icon1)
        self.actionNext.setObjectName("actionNext")
        self.actionPrev = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/48x48/media-skip-backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrev.setIcon(icon2)
        self.actionPrev.setObjectName("actionPrev")
        self.actionRemove = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/32x32/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove.setIcon(icon3)
        self.actionRemove.setObjectName("actionRemove")
        self.actionPlay = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/48x48/media-playback-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay.setIcon(icon4)
        self.actionPlay.setObjectName("actionPlay")
        self.actionStop = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/48x48/media-playback-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon5)
        self.actionStop.setObjectName("actionStop")
        self.actionQuit = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/32x32/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon6)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNavigationUp = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/22x22/go-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNavigationUp.setIcon(icon7)
        self.actionNavigationUp.setObjectName("actionNavigationUp")
        self.actionNavigationHome = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/22x22/go-home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNavigationHome.setIcon(icon8)
        self.actionNavigationHome.setObjectName("actionNavigationHome")
        self.actionConfWizard = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/22x22/tools-wizard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfWizard.setIcon(icon9)
        self.actionConfWizard.setObjectName("actionConfWizard")
        self.menuQtimidity.addAction(self.actionQuit)
        self.menuPlaylist.addAction(self.actionPrev)
        self.menuPlaylist.addAction(self.actionPlay)
        self.menuPlaylist.addAction(self.actionStop)
        self.menuPlaylist.addAction(self.actionNext)
        self.menuPlaylist.addAction(self.actionRemove)
        self.menu_Go.addAction(self.actionNavigationHome)
        self.menu_Go.addAction(self.actionNavigationUp)
        self.menuSettings.addAction(self.actionConfWizard)
        self.menubar.addAction(self.menuQtimidity.menuAction())
        self.menubar.addAction(self.menu_Go.menuAction())
        self.menubar.addAction(self.menuPlaylist.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Qtimidity", None, QtGui.QApplication.UnicodeUTF8))
        self.prevButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.playButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuQtimidity.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlaylist.setTitle(QtGui.QApplication.translate("MainWindow", "&Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Go.setTitle(QtGui.QApplication.translate("MainWindow", "&Go", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setText(QtGui.QApplication.translate("MainWindow", "&Next Track", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrev.setText(QtGui.QApplication.translate("MainWindow", "&Previous Track", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove.setText(QtGui.QApplication.translate("MainWindow", "&Remove From Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove.setShortcut(QtGui.QApplication.translate("MainWindow", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setText(QtGui.QApplication.translate("MainWindow", "P&lay Track", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setText(QtGui.QApplication.translate("MainWindow", "&Stop Track", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNavigationUp.setText(QtGui.QApplication.translate("MainWindow", "&Up", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNavigationHome.setText(QtGui.QApplication.translate("MainWindow", "&Home", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfWizard.setText(QtGui.QApplication.translate("MainWindow", "Config &Wizard", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

